### ISSUE TITLE
Sidebar is not scrollable

### ISSUE THREAD

**Issue by josh-works** [turingschool-examples/module_0_capstone#168]
After adding descriptions to each day in the sidebar, it looks like one cannot scroll up/down the sidebar to access material at the bottom of the page.

Here's what it looks like for me:
![not scrollable](https://cl.ly/39870a9b1f5d/Screen%20Recording%202019-08-05%20at%2008.13%20AM.gif)

(When my cursor is on the left, over the sidebar, I'm scrolling with my mouse, but it still moves the primary page, not the sidebar)

This is on any page in http://mod0.turing.io/

A successful fix would be (imo) if it were possible to scroll down to the bottom of the sidebar.

**Comment by damwhit** [comment]
Sorry I didn't catch this update before. But I'm thinking it may be best to leave the descriptions out of the sidebar to keep it simple, and leave no need for having overflow scroll on the left. I'm making quite a few updates to curriculum for the upcoming mod and will do this.

**Comment by josh-works** [comment]
agreed; I'd love to see some descriptors in the sidebar some day, but its more important that the sidebar be usable than descriptive.

**Comment by damwhit** [comment]
@josh-works totally agree on the above. Once we get the curriculum more nailed down after this next 3-6 weeks we can re-evaluate.
